---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
      when: ansible_os_family == "Debian"

  roles:
    - { role: common-tools, tags: ['common-tools', 'tools'] }
    - { role: snap-apps, tags: ['snapd', 'tools'] }
    - { role: vim, tags: ['vim', 'tools'] }
    - { role: tmux, tags: ['tmux', 'terminal'] }
    - { role: zsh, tags: ['zsh', 'terminal'] }
    - { role: i3, tags: ['i3', 'wm'] }
    - { role: pnpm, tags: ['pnpm', 'nodejs'] }
    - { role: fonts, tags: ['fonts', 'system'] }

  post_tasks:
    - name: Display completion message
      debug:
        msg: "Development environment setup completed successfully!"
