---
- name: Display OS Information
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Display detected operating system
      debug:
        msg: "Detected OS: {{ ansible_os_family }} ({{ ansible_distribution }} {{ ansible_distribution_version }})"

- name: Run Linux setup
  import_playbook: linux/site.yml
  when: ansible_os_family == "Debian"

- name: Run macOS setup
  import_playbook: macos/site.yml
  when: ansible_os_family == "Darwin"
